.\" generated with Ronn/v0.6.8
.\" http://github.com/rtomayko/ronn/
.
.TH "RDISCOUNT" "1" "April 2010" "" "RUBY"
.
.SH "NAME"
\fBrdiscount\fR \- humane markup to HTML conversion tool
.
.SH "SYNOPSIS"
\fBrdiscount\fR [\fIfile\fR\.\.\.]
.
.SH "DESCRIPTION"
The \fBrdiscount\fR utility reads one or more markdown(7)\-formatted text \fIfile\fRs and writes HTML to standard output\. With no \fIfile\fR, or when \fIfile\fR is \'\-\', \fBrdiscount\fR reads source text from standard input\.
.
.SH "RETURN VALUES"
The \fBrdiscount\fR utility exits 0 on success, and > 0 if an error occurs\.
.
.SH "SEE ALSO"
markdown(7)
.
.SH "AUTHOR"
Ryan Tomayko \fIhttp://tomayko\.com/about\fR
