namespace :sammy do
  namespace :backend_example do 
    task :start => :copy_files do
      system 'open http://localhost:9393/'
      system 'shotgun app.ru'
    end
    
    desc 'copy latest sammy and jquery from lib and vendor'
    task :copy_files do
      root = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
      {
        ['lib', 'sammy.js'] => 'sammy.js',
        ['vendor', 'jquery-1.3.2.min.js'] => 'jquery.js'
      }.each do |from, to|
        FileUtils.cp(File.join(root, *from), File.join('public', 'javascripts', to))
      end
    end
  end
end